repos:
    - repo: local
      hooks:
        - id: check-https
          name: check-https
          entry: python _hooks/check_https.py
          language: python
          files: '.*\.(md|markdown)'
