repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace # Removes trailing white spaces
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: end-of-file-fixer
