show_excerpts: true
title: Cook & Code
description: >- # this means to ignore newlines until "baseurl:"
  Personal projects and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  roald87
linkedin_username: roaldruiter

texture:
  title: Cook & Code
  tagline: Personal projects and ideas.
  date_format: "%b %-d, %Y"
  style: black
  
  showNav: true
  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"
    - title: Tags
      url: "/tags" 
    - title: TwinCAT
      url: "/twincat" 
    - title: Cooking
      url: "/cooking" 
       
  social_links:
    github:  roald87
    linkedIn: in/roaldruiter
    rss: feed

feed:
  categories:
    - twincat
    - cooking

# Build settings
markdown: kramdown
remote_theme: roald87/texture
plugins:
  - jekyll-feed
  - jemoji
